import type { Lead, Playbook, Research, Draft } from "./types";
import { validatedResearch, validatedDraft } from "./validation";
export type Usage={tokens:number;costUsd:number;model:string};
function scoreLead(lead:Lead,playbook:Playbook):Research{const blob=`${lead.name} ${lead.email} ${lead.company} ${lead.title} ${lead.message}`.toLowerCase();const reasons:string[]=[];let score=40,disqualified=false;if(lead.company.trim()){score+=15;reasons.push("Company name present");}if(lead.title.trim()){score+=10;reasons.push("Role present");}if(lead.message.trim().length>20){score+=15;reasons.push("Wrote a real note");}if(["founder","ceo","owner","partner","sales","growth","head"].some(w=>blob.includes(w))){score+=10;reasons.push("Decision-adjacent title");}const dq=playbook.disqualify.toLowerCase().split(/[,;\n]/).map(s=>s.trim()).filter(Boolean);if(dq.some(w=>w.length>3&&blob.includes(w))){disqualified=true;score=Math.min(score,25);reasons.push("Matches disqualify rule");}if(/(student|internship|job application|cv attached)/i.test(blob)){disqualified=true;score=10;reasons.push("Looks like inbound job seeker");}const companyGuess=lead.company||lead.email.split("@")[1]||"Unknown firm";const likelyNeed=lead.message.trim()?lead.message.trim().slice(0,220):`Inbound from ${companyGuess}. Fit vs ICP: ${playbook.icpFirm}, ${playbook.icpSize}.`;return{companyGuess,likelyNeed,score:Math.max(0,Math.min(100,score)),reasons,disqualified};}
function draftFromPlaybook(lead:Lead,p:Playbook,r:Research):Draft{const first=lead.name.split(" ")[0]||"there";const subject=r.disqualified?`Thanks ${first} — quick note`:`${p.companyName} / ${lead.company||"your note"}`;const quoted=lead.message?`You wrote: "${lead.message.slice(0,160)}"\n\n`:"";const body=r.disqualified?`Hi ${first},\n\nThanks for writing in. This does not look like a fit for what we sell (${p.offer}).\n\nIf I have that wrong, reply and I will pick it up.\n\n${p.senderName}\n${p.senderTitle}\n${p.companyName}\n`:`Hi ${first},\n\nThanks for the note${lead.company?` from ${lead.company}`:""}. ${p.firstEmailGoal}\n\n${p.offer}\n\n${quoted}If useful I can walk through how approval works on a short call.\n\n${p.senderName}\n${p.senderTitle}\n${p.companyName}\n${p.companyUrl}\n`;return{subject,body,reason:r.disqualified?"Low score / disqualified — polite close, no meeting.":`Score ${r.score}. First email asks to confirm the request, no price promise.`};}
function parseJsonBlock(text:string){const match=text.match(/\{[\s\S]*\}/);if(!match)return null;try{return JSON.parse(match[0]) as Record<string,unknown>}catch{return null}}
async function openaiJSON(prompt:string){const key=process.env.OPENAI_API_KEY;if(!key)return null;const model=process.env.OPENAI_MODEL||"gpt-4o-mini";const res=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${key}`},body:JSON.stringify({model,temperature:.3,messages:[{role:"user",content:prompt}]})});if(!res.ok)return{json:null,usage:{tokens:0,costUsd:0,model:"openai-error"}};const data=await res.json() as {choices?:{message?:{content?:string}}[];usage?:{prompt_tokens?:number;completion_tokens?:number}};const input=data.usage?.prompt_tokens??0,output=data.usage?.completion_tokens??0;return{json:parseJsonBlock(data.choices?.[0]?.message?.content??""),usage:{tokens:input+output,costUsd:input/1e6*.15+output/1e6*.6,model}};}
async function claudeJSON(prompt:string){const key=process.env.ANTHROPIC_API_KEY;if(!key)return null;const model=process.env.ANTHROPIC_MODEL||"claude-sonnet-4-20250514";const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"content-type":"application/json","x-api-key":key,"anthropic-version":"2023-06-01"},body:JSON.stringify({model,max_tokens:800,messages:[{role:"user",content:prompt}]})});if(!res.ok)return{json:null,usage:{tokens:0,costUsd:0,model:"claude-error"}};const data=await res.json() as {content?:{type:string;text?:string}[];usage?:{input_tokens?:number;output_tokens?:number}};const input=data.usage?.input_tokens??0,output=data.usage?.output_tokens??0;return{json:parseJsonBlock(data.content?.find(b=>b.type==="text")?.text??""),usage:{tokens:input+output,costUsd:input/1e6*3+output/1e6*15,model}};}
async function llmJSON(prompt:string){return await openaiJSON(prompt)||await claudeJSON(prompt)||{json:null,usage:{tokens:0,costUsd:0,model:"stub"}};}
export async function runResearchAndDraft(lead:Lead,playbook:Playbook){const fallbackResearch=scoreLead(lead,playbook);const fallbackDraft=draftFromPlaybook(lead,playbook,fallbackResearch);const{json:llm,usage}=await llmJSON(`Return ONLY JSON with research and draft objects. Never invent prices outside the playbook. Never claim the email was sent. Language: ${playbook.language}. Tone: ${playbook.tone}.\nPlaybook:${JSON.stringify(playbook)}\nLead:${JSON.stringify({name:lead.name,email:lead.email,company:lead.company,title:lead.title,message:lead.message})}`);const parsed=(llm??{}) as {research?:unknown;draft?:unknown};const research=validatedResearch(parsed.research,fallbackResearch);const draft=validatedDraft(parsed.draft,fallbackDraft);return{research,draft,usage};}
