import type { Connections, Job, Lead, Playbook, Store } from "./types";
import { getAuthContext } from "./auth";
import { decryptJson, encryptJson } from "./secrets";
export function supabaseConfigured(){return Boolean((process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL)&&process.env.SUPABASE_SERVICE_ROLE_KEY);}
function config(){const url=(process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL||"").replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY||"";if(!url||!key)throw new Error("Supabase server configuration is missing");return{url,key};}
async function rest<T>(path:string,init:RequestInit={}):Promise<T>{const{url,key}=config();const res=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,authorization:`Bearer ${key}`,"content-type":"application/json",prefer:"return=representation",...(init.headers??{})},cache:"no-store"});if(!res.ok){const text=await res.text();throw new Error(`Supabase ${res.status}: ${text.slice(0,300)}`);}if(res.status===204)return[] as T;return(await res.json()) as T;}
export function supabaseAdmin(){return{rest};}
type LeadRow={id:string;created_at:string;source:Lead["source"];name:string;email:string;company:string;title:string;message:string;status:Lead["status"];research:Lead["research"];draft:Lead["draft"];events:Lead["events"];thread:Lead["thread"];intent:Lead["intent"];slots:Lead["slots"];tokens:number;cost_usd:number;gmail_id:string|null;gmail_thread_id:string|null;hubspot_contact_id:string|null};
type JobRow={id:string;type:Job["type"];lead_id:string;status:Job["status"];detail:string;created_at:string;finished_at?:string|null;idempotency_key?:string|null};
function toLead(r:LeadRow):Lead{return{id:r.id,createdAt:r.created_at,source:r.source,name:r.name,email:r.email,company:r.company??"",title:r.title??"",message:r.message??"",status:r.status,research:r.research,draft:r.draft,events:r.events??[],thread:r.thread??[],intent:r.intent??null,slots:r.slots??[],tokens:Number(r.tokens??0),costUsd:Number(r.cost_usd??0),gmailId:r.gmail_id??undefined,gmailThreadId:r.gmail_thread_id??undefined,hubspotContactId:r.hubspot_contact_id??undefined};}
function fromLead(l:Lead,org:string){return{id:l.id,organization_id:org,created_at:l.createdAt,source:l.source,name:l.name,email:l.email,company:l.company,title:l.title,message:l.message,status:l.status,research:l.research,draft:l.draft,events:l.events??[],thread:l.thread??[],intent:l.intent,slots:l.slots??[],tokens:l.tokens??0,cost_usd:l.costUsd??0,gmail_id:l.gmailId??null,gmail_thread_id:l.gmailThreadId??null,hubspot_contact_id:l.hubspotContactId??null};}
function toJob(r:JobRow):Job{return{id:r.id,type:r.type,leadId:r.lead_id,status:r.status,detail:r.detail,createdAt:r.created_at,finishedAt:r.finished_at??undefined,idempotencyKey:r.idempotency_key??undefined};}
function fromJob(j:Job,org:string){return{id:j.id,organization_id:org,type:j.type,lead_id:j.leadId,status:j.status,detail:j.detail,idempotency_key:j.idempotencyKey??null,created_at:j.createdAt,finished_at:j.finishedAt??null};}
function decryptConnection(value:unknown):Connections["gmail"]{if(!value)return null;if(typeof value==="object"&&value!==null&&"v" in value)return decryptJson<Connections["gmail"]>(value);return value as Connections["gmail"];}
export async function readRemote():Promise<Partial<Store>>{const{organizationId}=await getAuthContext();const[books,conns,leads,jobs]=await Promise.all([rest<{data:Playbook}[]>(`org_playbooks?organization_id=eq.${organizationId}`),rest<{gmail:unknown;hubspot_token:string}[]>(`org_connections?organization_id=eq.${organizationId}`),rest<LeadRow[]>(`leads?organization_id=eq.${organizationId}&order=created_at.desc`),rest<JobRow[]>(`jobs?organization_id=eq.${organizationId}&order=created_at.desc`)]);return{playbook:books[0]?.data,connections:conns[0]?{gmail:decryptConnection(conns[0].gmail),hubspotToken:conns[0].hubspot_token??""}:undefined,leads:(leads??[]).map(toLead),jobs:(jobs??[]).map(toJob)};}
export async function writeRemote(store:Store){const{organizationId}=await getAuthContext();await rest(`org_playbooks?organization_id=eq.${organizationId}`,{method:"POST",headers:{prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({organization_id:organizationId,data:store.playbook,updated_at:new Date().toISOString()})});await rest(`org_connections?organization_id=eq.${organizationId}`,{method:"POST",headers:{prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({organization_id:organizationId,gmail:store.connections.gmail?encryptJson(store.connections.gmail):null,hubspot_token:store.connections.hubspotToken,updated_at:new Date().toISOString()})});if(store.leads.length)await rest("leads",{method:"POST",headers:{prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(store.leads.map(l=>fromLead(l,organizationId)))});if(store.jobs.length)await rest("jobs",{method:"POST",headers:{prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(store.jobs.map(j=>fromJob(j,organizationId)))});}
export{rest};
