import { adminRest } from "./supabase-admin";
import { defaultPlaybook } from "./store";
import { classifyReply, draftAfterReply } from "./closer";
import type { Lead, Playbook } from "./types";

function orgId(){const value=process.env.GREENLIT_WEBHOOK_ORG_ID;if(!value)throw new Error("GREENLIT_WEBHOOK_ORG_ID is required for webhook ingestion");return value;}
async function playbook():Promise<Playbook>{const rows=await adminRest<{data:Playbook}[]>(`org_playbooks?organization_id=eq.${orgId()}&limit=1`);return rows[0]?.data?{...defaultPlaybook,...rows[0].data}:defaultPlaybook;}
export async function createWebhookLead(input:{name:string;email:string;company:string;title:string;message:string}){const lead:Lead={id:crypto.randomUUID(),createdAt:new Date().toISOString(),source:"webhook",name:input.name,email:input.email,company:input.company,title:input.title,message:input.message,status:"new",research:null,draft:null,events:[{at:new Date().toISOString(),type:"created",detail:"Source: webhook"}],thread:[],intent:null,slots:[],tokens:0,costUsd:0};const rows=await adminRest<{id:string;status:Lead["status"]}[]>("leads",{method:"POST",body:JSON.stringify({id:lead.id,organization_id:orgId(),created_at:lead.createdAt,source:lead.source,name:lead.name,email:lead.email,company:lead.company,title:lead.title,message:lead.message,status:lead.status,research:null,draft:null,events:lead.events,thread:[],intent:null,slots:[],tokens:0,cost_usd:0}),headers:{prefer:"return=representation"}});return rows[0]??lead;}
export async function ingestWebhookReply(leadId:string,text:string,gmailId?:string,threadId?:string){const rows=await adminRest<Lead[]>(`leads?id=eq.${leadId}&organization_id=eq.${orgId()}&limit=1`);const lead=rows[0];if(!lead)throw new Error("Lead not found");const thread=lead.thread??[];if(gmailId&&thread.some(m=>m.gmailId===gmailId))return;const incoming=text.trim();if(!incoming)return;const p=await playbook();thread.push({at:new Date().toISOString(),direction:"in",body:incoming,gmailId,threadId});if(threadId)lead.gmailThreadId=threadId;if(lead.status==="sent"||lead.status==="approved")lead.status="replied";lead.events=[{at:new Date().toISOString(),type:"replied",detail:incoming.slice(0,180)},...(lead.events??[])];const intent=classifyReply(incoming);lead.intent=intent;const next=draftAfterReply(lead,p,intent,incoming);lead.draft=next.draft;lead.slots=next.slots;lead.status=next.needsHuman?"needs_human":"waiting_approval";if(next.needsHuman)lead.events.unshift({at:new Date().toISOString(),type:"needs_human",detail:next.draft.reason});else lead.events.unshift({at:new Date().toISOString(),type:"draft",detail:`Follow-up (${intent})`});await adminRest(`leads?id=eq.${leadId}&organization_id=eq.${orgId()}`,{method:"PATCH",body:JSON.stringify({status:lead.status,thread:lead.thread,gmail_thread_id:lead.gmailThreadId??null,intent:lead.intent,draft:lead.draft,slots:lead.slots,events:lead.events}),headers:{prefer:"return=minimal"}});}
